# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'writingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from CONSTANTS import buttonStyle, textStyle, fadeStyle


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        x, y = 1920, 1080
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(x, y)
        MainWindow.setStyleSheet("background: #FFFFFF")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(849, 649, 262, 105))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setStyleSheet(buttonStyle)
        self.startButton.setObjectName("startButton")
        self.mainText = QtWidgets.QLabel(self.centralwidget)
        self.mainText.setGeometry(QtCore.QRect(x // 2 - 1336 // 2, y // 2 - 185 // 2 - 262, 1336, 185))
        self.mainText.setObjectName("mainText")
        self.mainText.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.mainText.setStyleSheet(textStyle)
        self.mainLine = QtWidgets.QLineEdit(self.centralwidget)
        self.mainLine.setGeometry(QtCore.QRect(260, 471, 1400, 40))
        self.mainLine.setObjectName("mainLine")
        self.mainLine.setStyleSheet(textStyle)
        self.timerView = QtWidgets.QLabel(self.centralwidget)
        self.timerView.setGeometry(QtCore.QRect(795, 573, 330, 48))
        self.timerView.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.timerView.setObjectName("timerView")
        self.timerView.setStyleSheet(textStyle)
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(1111, 884, 255, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(26)
        sizePolicy.setVerticalStretch(105)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setStyleSheet(buttonStyle)
        self.settingsButton.setObjectName("settingsButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(1397, 884, 209, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(26)
        sizePolicy.setVerticalStretch(105)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setStyleSheet(buttonStyle)
        self.stopButton.setObjectName("stopButton")
        self.menuButton = QtWidgets.QPushButton(self.centralwidget)
        self.menuButton.setGeometry(QtCore.QRect(1637, 884, 209, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(26)
        sizePolicy.setVerticalStretch(105)
        sizePolicy.setHeightForWidth(self.menuButton.sizePolicy().hasHeightForWidth())
        self.menuButton.setSizePolicy(sizePolicy)
        self.menuButton.setStyleSheet(buttonStyle)
        self.menuButton.setObjectName("menuButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Начать"))
        self.mainText.setText(_translate("MainWindow", "TextLabel"))
        self.timerView.setText(_translate("MainWindow", "timer"))
        self.settingsButton.setText(_translate("MainWindow", "Настройки"))
        self.stopButton.setText(_translate("MainWindow", "Стоп"))
        self.menuButton.setText(_translate("MainWindow", "Меню"))
