# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from const.CONSTANTS import loginWindow_styles


class LoginWindow(QtWidgets.QWidget):
    def setupUi(self, QWidget):
        QWidget.setObjectName("MainWindow")
        QWidget.resize(1395, 904)
        self.setStyleSheet(loginWindow_styles)
        self.centralwidget = QtWidgets.QWidget(QWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(456, 163, 1007, 168))
        self.welcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label.setObjectName("welcome_label")
        self.bgLabel = QtWidgets.QLabel(self.centralwidget)
        self.bgLabel.setGeometry(QtCore.QRect(456, 362, 1007, 515))
        self.bgLabel.setText("")
        self.bgLabel.setObjectName("bgLabel")
        self.nameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(686, 518, 547, 46))
        self.nameEdit.setObjectName("nameEdit")
        self.nameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEdit.setGeometry(QtCore.QRect(686, 640, 546, 47))
        self.passwordEdit.setObjectName("passWordEdit")
        self.passwordEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.createAccount = QtWidgets.QPushButton(self.centralwidget)
        self.createAccount.setGeometry(QtCore.QRect(765, 765, 389, 68))
        self.createAccount.setObjectName("createAccount")
        QWidget.setCentralWidget(self.centralwidget)

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcome_label.setText(_translate("MainWindow", "Добро пожаловать в Faster, давайте\nзарегистрируемся?"))
        self.createAccount.setText("Создать аккаунт")
        self.nameEdit.setPlaceholderText('Введите ваше имя')
        self.passwordEdit.setPlaceholderText('Введите ваш пароль')
