# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

class MenuWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.trainsView = QtWidgets.QListWidget(Form)
        self.trainsView.setGeometry(QtCore.QRect(1920 // 2 - 600, 0, 1200, 1020))

        self.trainsView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.trainsView.verticalScrollBar().hide()
        self.trainsView.setResizeMode(QtWidgets.QListView.Fixed)
        self.trainsView.setLayoutMode(QtWidgets.QListView.Batched)
        self.trainsView.setGridSize(QtCore.QSize(1007, 120))
        self.trainsView.setViewMode(QtWidgets.QListView.ListMode)
        self.trainsView.setUniformItemSizes(True)
        self.trainsView.setWordWrap(False)
        self.trainsView.setSelectionRectVisible(False)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(553, 20, 813, 75))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.settingsButton = QtWidgets.QPushButton(Form)
        self.settingsButton.setGeometry(QtCore.QRect(1609, 901, 255, 81))
        # self.settingsButton.setStyleSheet(buttonStyle)
        self.settingsButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        __sortingEnabled = self.trainsView.isSortingEnabled()
        self.trainsView.setSortingEnabled(False)
        self.trainsView.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "Выберите тренировку"))
        self.settingsButton.setText(_translate("Form", "Настройки"))
