# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'writingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class WritingWindow(QtWidgets.QWidget):
    def setupUi(self, QWidget):
        x, y = 1920, 1080
        QWidget.setObjectName("MainWindow")
        QWidget.resize(x, y)
        QWidget.setStyleSheet("background: #FFFFFF")
        self.centralwidget = QtWidgets.QWidget(QWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(767, 649, 386, 105))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setObjectName("startButton")
        self.previousLineView = QtWidgets.QLabel(self.centralwidget)
        self.previousLineView.setGeometry(QtCore.QRect(x // 2 - 1336 // 2, y // 2 - 186 // 2 - 262, 1336, 186 // 3))
        self.previousLineView.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.previousLineView.setText('previousLineView')
        self.currentLineView = QtWidgets.QLabel(self.centralwidget)
        self.currentLineView.setGeometry(
            QtCore.QRect(x // 2 - 1336 // 2, y // 2 - 186 // 2 - 262 + 186 // 3, 1336, 186 // 3))
        self.currentLineView.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.currentLineView.setObjectName('currentLineView')
        self.nextLineView = QtWidgets.QLabel(self.centralwidget)
        self.nextLineView.setGeometry(
            QtCore.QRect(x // 2 - 1336 // 2, y // 2 - 186 // 2 - 262 + 186 // 3 * 2, 1336, 186 // 3))
        self.nextLineView.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.nextLineView.setText('nextLineView')
        self.showData = QtWidgets.QLabel(self.centralwidget)
        self.showData.setGeometry(QtCore.QRect(894, 520, 132, 39))
        self.showData.setObjectName("showData")
        self.showData.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        # self.showData.setStyleSheet(textStyle)
        self.mainLine = QtWidgets.QLineEdit(self.centralwidget)
        self.mainLine.setGeometry(QtCore.QRect(260, 471, 1400, 40))
        self.mainLine.setObjectName("mainLine")
        self.mainLine.setAlignment(QtCore.Qt.AlignCenter)
        self.timerView = QtWidgets.QLabel(self.centralwidget)
        self.timerView.setGeometry(QtCore.QRect(795, 573, 330, 48))
        self.timerView.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.timerView.setObjectName("timerView")
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(1046, 884, 262, 105))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(26)
        sizePolicy.setVerticalStretch(105)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setObjectName("settingsButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(1630, 884, 262, 105))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(26)
        sizePolicy.setVerticalStretch(105)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setObjectName("stopButton")
        self.menuButton = QtWidgets.QPushButton(self.centralwidget)
        self.menuButton.setGeometry(QtCore.QRect(1338, 884, 262, 105))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(26)
        sizePolicy.setVerticalStretch(105)
        sizePolicy.setHeightForWidth(self.menuButton.sizePolicy().hasHeightForWidth())
        self.menuButton.setSizePolicy(sizePolicy)
        self.menuButton.setObjectName("menuButton")
        QWidget.setCentralWidget(self.centralwidget)

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Начать"))
        self.currentLineView.setText(_translate("MainWindow", "TextLabel"))
        self.timerView.setText(_translate("MainWindow", "timer"))
        self.settingsButton.setText(_translate("MainWindow", "Настройки"))
        self.stopButton.setText(_translate("MainWindow", "Стоп"))
        self.menuButton.setText(_translate("MainWindow", "Меню"))
        self.showData.setToolTip('Замочек показывает возможность вводить текст в строку')
        self.mainLine.setPlaceholderText('Нажмите начать чтобы начать')
